const EDUCATION_ENUM = [
  'High School Diploma',
  'Associate of Arts (AA)',
  'Associate of Science (AS)',
  'Associate of Applied Science (AAS)',
  'Bachelor of Arts (BA)',
  'Bachelor of Science (BS)',
  'Bachelor of Fine Arts (BFA)',
  'Bachelor of Business Administration (BBA)',
  'Bachelor of Engineering (BEng)',
  'Bachelor of Technology (BTech)',
  'Master of Arts (MA)',
  'Master of Science (MS or MSc)',
  'Master of Business Administration (MBA)',
  'Master of Fine Arts (MFA)',
  'Master of Education (MEd)',
  'Master of Engineering (MEng)',
  'Master of Technology (MTech)',
  'Master of Public Health (MPH)',
  'Master of Social Work (MSW)',
  'Doctor of Philosophy (PhD)',
  'Doctor of Education (EdD)',
  'Doctor of Business Administration (DBA)',
  'Doctor of Medicine (MD)',
  'Doctor of Dental Surgery (DDS)',
  'Doctor of Juridical Science (SJD)',
  'Project Management Professional (PMP)',
  'Certified Public Accountant (CPA)',
  'Certified Information Systems Security Professional (CISSP)',
  'Chartered Financial Analyst (CFA)',
  'Professional Engineering License (PE)',
];
const CERTIFICATION_ENUM = [
  'Project Management Professional (PMP)',
  'Certified Public Accountant (CPA)',
  'Certified Information Systems Security Professional (CISSP)',
  'Chartered Financial Analyst (CFA)',
  'Professional Engineering License (PE)',
  'Certified Scrum Master (CSM)',
  'Cisco Certified Network Associate (CCNA)',
  'Cisco Certified Internetwork Expert (CCIE)',
  'Microsoft Certified Solutions Expert (MCSE)',
  'Amazon Web Services Certified Solutions Architect (AWS CSA)',
  'Google Cloud Professional Data Engineer',
  'Certified Ethical Hacker (CEH)',
  'Six Sigma Black Belt',
  'Certified Information Systems Auditor (CISA)',
  'Certified Information Security Manager (CISM)',
  'Salesforce Certified Administrator',
  'Adobe Certified Expert (ACE)',
  'CompTIA A+',
  'CompTIA Network+',
  'CompTIA Security+',
  'ITIL Foundation',
  'Oracle Certified Professional (OCP)',
  'Red Hat Certified Engineer (RHCE)',
  'Lean Six Sigma Green Belt',
  'Financial Risk Manager (FRM)',
  'Hootsuite Social Marketing Certification',
  'Google Analytics Individual Qualification (GAIQ)',
  'HubSpot Content Marketing Certification',
  'Amazon Web Services Certified Developer (AWS CD)',
  'Certified in Risk and Information Systems Control (CRISC)',
  'Certified Supply Chain Professional (CSCP)',
  'Certified Management Accountant (CMA)',
  'AWS Certified SysOps Administrator',
  'Certified Cloud Security Professional (CCSP)',
  'Google Cloud Professional Cloud Architect',
  'Cisco Certified Design Professional (CCDP)',
  'Certified Kubernetes Administrator (CKA)',
  'Microsoft Certified Azure Solutions Architect',
  'Certified Financial Planner (CFP)',
  'Certified Business Analysis Professional (CBAP)',
  'Scrum Alliance Certified Scrum Product Owner (CSPO)',
  'SAS Certified Data Scientist',
  'Certified Data Management Professional (CDMP)',
  'Certified Fraud Examiner (CFE)',
  'Certified Digital Marketing Professional (CDMP)',
  'PRINCE2 Foundation and Practitioner',
  'TOGAF 9 Certification',
  'Certified Healthcare Information Systems (CHIS)',
  'Certified Information Privacy Professional (CIPP)',
];
const WORK_PREFERENCE_ENUM = {
  remote: 'Remote',
  on_site: 'On-Site',
};
module.exports = { EDUCATION_ENUM, CERTIFICATION_ENUM, WORK_PREFERENCE_ENUM };
