const { hashSync } = require('bcryptjs');
module.exports = () => [
  {
    name: 'Lars Müller',
    email: 'lars.mueller@example.com',
    city: 'Berlin',
    country: 'Germany',
    password: hashSync('supersecretpassword'),
    active: true,
    confirmed: true,
    phoneNumber: '030-1234567',
    description: 'Software developer from Berlin',
    confirmedAt: new Date('2023-01-15T10:00:00Z'),
  },
  {
    name: 'Sophie Dubois',
    email: 'sophie.dubois@example.com',
    city: 'Paris',
    country: 'France',
    password: hashSync('supersecretpassword'),
    active: true,
    confirmed: true,
    phoneNumber: '01-2345678',
    description: 'Graphic designer from Paris',
    confirmedAt: null,
  },
  {
    name: 'Giovanni Rossi',
    email: 'giovanni.rossi@example.com',
    city: 'Rome',
    country: 'Italy',
    password: hashSync('supersecretpassword'),
    active: true,
    confirmed: true,
    phoneNumber: '06-3456789',
    description: 'Architect from Rome',
    confirmedAt: new Date('2023-02-20T10:00:00Z'),
  },
  {
    name: 'Ana Martínez',
    email: 'ana.martinez@example.com',
    city: 'Madrid',
    country: 'Spain',
    password: hashSync('supersecretpassword'),
    active: true,
    confirmed: true,
    phoneNumber: '91-4567890',
    description: 'Marketing specialist from Madrid',
    confirmedAt: null,
  },
  {
    name: 'Katarzyna Nowak',
    email: 'katarzyna.nowak@example.com',
    city: 'Warsaw',
    country: 'Poland',
    password: hashSync('supersecretpassword'),
    active: true,
    confirmed: true,
    phoneNumber: '22-5678901',
    description: 'Data analyst from Warsaw',
    confirmedAt: new Date('2023-03-25T12:00:00Z'),
  },
];
