const Client = require('../../models/client');

module.exports = async () => {
  const clients = await Client.find().lean();
  return [
    {
      title: 'Web Development Project',
      startDate: new Date('2023-07-01'),
      endDate: new Date('2023-09-01'),
      description:
        'Looking for an experienced web developer to build a responsive website for an e-commerce platform.',
      budget: 5000,
      country: 'Germany',
      city: 'Berlin',
      education: 'Bachelor of Science (BS)',
      skillsRequired: ['Web Development', 'SEO'],
      client: clients[Math.floor(Math.random() * clients.length)]._id,
      type: 'Remote',
    },
    {
      title: 'Graphic Design for Marketing Campaign',
      startDate: new Date('2023-07-10'),
      endDate: new Date('2023-08-10'),
      description:
        'Need a graphic designer to create visuals for a marketing campaign. Experience in Adobe Suite required.',
      budget: 3000,
      country: 'France',
      city: 'Paris',
      education: 'Bachelor of Fine Arts (BFA)',
      skillsRequired: ['Graphic Design', 'Digital Marketing'],
      client: clients[Math.floor(Math.random() * clients.length)]._id,
      type: 'Remote',
    },
    {
      title: 'Content Writing for Blog',
      startDate: new Date('2023-07-15'),
      endDate: new Date('2023-10-15'),
      description: 'Seeking a content writer to produce engaging blog posts for our tech website.',
      budget: 2000,
      country: 'Spain',
      city: 'Madrid',
      education: 'Bachelor of Arts (BA)',
      skillsRequired: ['Content Writing', 'SEO'],
      client: clients[Math.floor(Math.random() * clients.length)]._id,
      type: 'Remote',
    },
    {
      title: 'SEO Specialist Needed',
      startDate: new Date('2023-08-01'),
      endDate: new Date('2023-11-01'),
      description:
        'We need an SEO specialist to improve our search engine rankings and drive organic traffic.',
      budget: 4000,
      country: 'Italy',
      city: 'Rome',
      education: 'Master of Science (MS or MSc)',
      skillsRequired: ['SEO', 'Digital Marketing'],
      client: clients[Math.floor(Math.random() * clients.length)]._id,
      type: 'Remote',
    },
    {
      title: 'Social Media Manager',
      startDate: new Date('2023-07-20'),
      endDate: new Date('2023-12-20'),
      description:
        'Hiring a social media manager to create and manage social media content for our brand.',
      budget: 3500,
      country: 'Netherlands',
      city: 'Amsterdam',
      education: 'Bachelor of Business Administration (BBA)',
      skillsRequired: ['Social Media Management', 'Content Writing'],
      client: clients[Math.floor(Math.random() * clients.length)]._id,
      type: 'Remote',
    },
    {
      title: 'Video Editing for Online Course',
      startDate: new Date('2023-07-25'),
      endDate: new Date('2023-09-25'),
      description:
        'Looking for a video editor to create professional videos for our online education platform.',
      budget: 2500,
      country: 'Belgium',
      city: 'Brussels',
      education: 'Bachelor of Arts (BA)',
      skillsRequired: ['Video Editing', 'Content Writing'],
      client: clients[Math.floor(Math.random() * clients.length)]._id,
      type: 'Remote',
    },
    {
      title: 'Event Setup & Tear Down Services',
      startDate: new Date('2023-08-05'),
      endDate: new Date('2023-08-06'),
      description:
        'Need assistance with setting up and tearing down for an upcoming event in central Berlin.',
      budget: 1500,
      country: 'Germany',
      city: 'Berlin',
      education: 'High School Diploma',
      skillsRequired: ['Event Setup & Tear Down', 'Janitorial Services'],
      client: clients[Math.floor(Math.random() * clients.length)]._id,
      type: 'On-Site',
      address: '123 Event Venue, Berlin, Germany',
      coordinates: {
        lon: '13.4050',
        lat: '52.5200',
      },
    },
    {
      title: 'Plumbing Services Needed',
      startDate: new Date('2023-07-30'),
      endDate: new Date('2023-07-31'),
      description:
        'Looking for a skilled plumber to fix leaks and install new fixtures in our office building.',
      budget: 1000,
      country: 'France',
      city: 'Lyon',
      education: 'Associate of Applied Science (AAS)',
      skillsRequired: ['Plumbing', 'HVAC Services'],
      client: clients[Math.floor(Math.random() * clients.length)]._id,
      type: 'On-Site',
      address: '456 Business Park, Lyon, France',
      coordinates: {
        lon: '4.8357',
        lat: '45.7640',
      },
    },
    {
      title: 'Electrical Work for Renovation',
      startDate: new Date('2023-08-15'),
      endDate: new Date('2023-08-20'),
      description:
        'We need an electrician to help with the renovation of our office space, including wiring and lighting.',
      budget: 1200,
      country: 'Italy',
      city: 'Milan',
      education: 'Associate of Science (AS)',
      skillsRequired: ['Electrical Work', 'Construction Labor'],
      client: clients[Math.floor(Math.random() * clients.length)]._id,
      type: 'On-Site',
      address: '789 Office Building, Milan, Italy',
      coordinates: {
        lon: '9.1900',
        lat: '45.4642',
      },
    },
    {
      title: 'Home Inspection Services',
      startDate: new Date('2023-07-05'),
      endDate: new Date('2023-07-06'),
      description:
        'Looking for a certified home inspector to assess the condition of a property before purchase.',
      budget: 800,
      country: 'Spain',
      city: 'Barcelona',
      education: 'Bachelor of Science (BS)',
      skillsRequired: ['Home Inspection', 'Pest Control'],
      client: clients[Math.floor(Math.random() * clients.length)]._id,
      type: 'On-Site',
      address: '101 Real Estate Ave, Barcelona, Spain',
      coordinates: {
        lon: '2.1734',
        lat: '41.3851',
      },
    },
    {
      title: 'Landscaping for Office Garden',
      startDate: new Date('2023-08-10'),
      endDate: new Date('2023-08-12'),
      description: 'Need a professional landscaper to redesign and maintain our office garden.',
      budget: 1800,
      country: 'Germany',
      city: 'Hamburg',
      education: 'Associate of Arts (AA)',
      skillsRequired: ['Landscaping', 'Masonry'],
      client: clients[Math.floor(Math.random() * clients.length)]._id,
      type: 'On-Site',
      address: '202 Business Gardens, Hamburg, Germany',
      coordinates: {
        lon: '9.9937',
        lat: '53.5511',
      },
    },
    {
      title: 'Photography for Product Launch',
      startDate: new Date('2023-07-15'),
      endDate: new Date('2023-07-17'),
      description:
        'Seeking a professional photographer to take high-quality photos for our upcoming product launch.',
      budget: 2200,
      country: 'Netherlands',
      city: 'Rotterdam',
      education: 'Bachelor of Fine Arts (BFA)',
      skillsRequired: ['Photography', 'Videography'],
      client: clients[Math.floor(Math.random() * clients.length)]._id,
      type: 'On-Site',
      address: '303 Creative Studio, Rotterdam, Netherlands',
      coordinates: {
        lon: '4.4792',
        lat: '51.9225',
      },
    },
    {
      title: 'Translation Services for Website',
      startDate: new Date('2023-07-20'),
      endDate: new Date('2023-08-20'),
      description: 'Need a translator to convert our website content from English to French.',
      budget: 1000,
      country: 'France',
      city: 'Nice',
      education: 'Master of Arts (MA)',
      skillsRequired: ['Translation', 'Content Writing'],
      client: clients[Math.floor(Math.random() * clients.length)]._id,
      type: 'Remote',
    },
    {
      title: 'Handyman for Home Repairs',
      startDate: new Date('2023-07-25'),
      endDate: new Date('2023-07-28'),
      description:
        'Looking for a reliable handyman to perform various home repairs and maintenance tasks.',
      budget: 900,
      country: 'Spain',
      city: 'Valencia',
      education: 'High School Diploma',
      skillsRequired: ['Handyman Services', 'Plumbing'],
      client: clients[Math.floor(Math.random() * clients.length)]._id,
      type: 'On-Site',
      address: '404 Residential Street, Valencia, Spain',
      coordinates: {
        lon: '-0.3774',
        lat: '39.4699',
      },
    },
    {
      title: 'Janitorial Services for Office',
      startDate: new Date('2023-08-01'),
      endDate: new Date('2023-08-02'),
      description: 'Need janitorial services to clean our office space twice a week.',
      budget: 600,
      country: 'Belgium',
      city: 'Antwerp',
      education: 'High School Diploma',
      skillsRequired: ['Janitorial Services', 'Cleaning Services'],
      client: clients[Math.floor(Math.random() * clients.length)]._id,
      type: 'On-Site',
      address: '505 Office Park, Antwerp, Belgium',
      coordinates: {
        lon: '4.4025',
        lat: '51.2194',
      },
    },
    {
      title: 'Sound System Setup for Event',
      startDate: new Date('2023-07-30'),
      endDate: new Date('2023-07-31'),
      description:
        'Looking for a professional to set up and manage the sound system for our upcoming conference.',
      budget: 1400,
      country: 'Germany',
      city: 'Munich',
      education: 'Associate of Applied Science (AAS)',
      skillsRequired: ['Sound System Setup', 'Stage Lighting Setup'],
      client: clients[Math.floor(Math.random() * clients.length)]._id,
      type: 'On-Site',
      address: '606 Conference Center, Munich, Germany',
      coordinates: {
        lon: '11.5810',
        lat: '48.1351',
      },
    },
    {
      title: 'HVAC Services for New Building',
      startDate: new Date('2023-08-15'),
      endDate: new Date('2023-08-20'),
      description:
        'Need HVAC services for the installation of heating and cooling systems in a new office building.',
      budget: 2500,
      country: 'Italy',
      city: 'Turin',
      education: 'Associate of Science (AS)',
      skillsRequired: ['HVAC Services', 'Electrical Work'],
      client: clients[Math.floor(Math.random() * clients.length)]._id,
      type: 'On-Site',
      address: '707 New Office Park, Turin, Italy',
      coordinates: {
        lon: '7.6869',
        lat: '45.0703',
      },
    },
    {
      title: 'Pest Control for Warehouse',
      startDate: new Date('2023-07-20'),
      endDate: new Date('2023-07-21'),
      description:
        'Looking for pest control services to eliminate rodents and insects in our warehouse.',
      budget: 800,
      country: 'Spain',
      city: 'Seville',
      education: 'High School Diploma',
      skillsRequired: ['Pest Control', 'Cleaning Services'],
      client: clients[Math.floor(Math.random() * clients.length)]._id,
      type: 'On-Site',
      address: '808 Warehouse District, Seville, Spain',
      coordinates: {
        lon: '-5.9845',
        lat: '37.3891',
      },
    },
    {
      title: 'Security System Installation',
      startDate: new Date('2023-08-01'),
      endDate: new Date('2023-08-03'),
      description: 'Need a professional to install a security system in our office building.',
      budget: 1200,
      country: 'France',
      city: 'Marseille',
      education: 'Associate of Applied Science (AAS)',
      skillsRequired: ['Security System Installation', 'Electrical Work'],
      client: clients[Math.floor(Math.random() * clients.length)]._id,
      type: 'On-Site',
      address: '909 Security Lane, Marseille, France',
      coordinates: {
        lon: '5.3698',
        lat: '43.2965',
      },
    },
    {
      title: 'Flooring Installation for Office',
      startDate: new Date('2023-08-10'),
      endDate: new Date('2023-08-15'),
      description: 'Looking for a professional to install new flooring in our office space.',
      budget: 1700,
      country: 'Germany',
      city: 'Stuttgart',
      education: 'Associate of Science (AS)',
      skillsRequired: ['Flooring Installation', 'Carpentry'],
      client: clients[Math.floor(Math.random() * clients.length)]._id,
      type: 'On-Site',
      address: '1010 Business Park, Stuttgart, Germany',
      coordinates: {
        lon: '9.1829',
        lat: '48.7758',
      },
    },
    {
      title: 'Demolition Services for Old Building',
      startDate: new Date('2023-07-05'),
      endDate: new Date('2023-07-10'),
      description:
        'Need demolition services to tear down an old building to make way for new construction.',
      budget: 3000,
      country: 'Italy',
      city: 'Naples',
      education: 'High School Diploma',
      skillsRequired: ['Demolition', 'Construction Labor'],
      client: clients[Math.floor(Math.random() * clients.length)]._id,
      type: 'On-Site',
      address: '1111 Construction Zone, Naples, Italy',
      coordinates: {
        lon: '14.2681',
        lat: '40.8518',
      },
    },
  ];
};
